model = "gpt-5.6-terra"
model_reasoning_effort = "medium"
# model_provider = "openrouter"

[model_providers.openrouter]
name = "Openrouter backend"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"
