#!/usr/bin/env sh

# Determine OS platform
UNAME=$(uname)
if [ "$UNAME" = 'Linux' ]; then

    # Try to determine specific distribution
    DISTRO=$(awk -F= '/^NAME/{print $2}' /etc/os-release | sed -e 's/^"//' -e 's/"$//')

    if [ "$DISTRO" = 'Ubuntu' ] || [ "$DISTRO" = 'Pop!_OS)' ]; then
        alias fd='fdfind'
    fi

elif [ "$UNAME" = 'Darwin' ]; then
    alias pwdf='finder-path'
    alias cdf='cd "$(finder-path)"'
    alias spotlight='mdfind -onlyin $(pwd)'
    alias show-dotfiles='defaults write com.apple.Finder AppleShowAllFiles -bool true && killall Finder'
    alias hide-dotfiles='defaults write com.apple.Finder AppleShowAllFiles -bool false && killall Finder'

    # On macOS, the shortcut sudoedit does not exist
    alias sudoedit='sudo -e'
fi

# Also expand aliases when running a sudo command
alias sudo='sudo '

if [ -x "$(command -v exa)" ]; then
    alias ls='exa --icons'
    alias ll='ls -l'
    alias la='ls -la'
fi

# Since the alacritty terminfo is most likley not installed on most remote servers
# we use the very common xterm-256color for ssh
alias ssh='env TERM=xterm-256color ssh'

alias cm='chezmoi'

# git aliases
alias ga='git add'
alias gcm='git commit -m'
alias gst='git status'
alias gd='git diff'
alias gp='git push'

# tmux aliases
alias ta='tmux attach -t'
alias tn='tmux new-session -s'
alias tl='tmux list-sessions'
alias tks='tmux kill-server'
alias td='tmux kill-session -t'

alias theme='cycle_base16'
alias nvim='~/.local/bin/nvim-macos/bin/nvim'

# Useful to compare with my own nvim config. Must be installed manually before
alias chad='NVIM_APPNAME=chad nvim'
alias astro='NVIM_APPNAME=astro nvim'
alias lazy='NVIM_APPNAME=lazyvim nvim'
