fontsize = 17.0
nerdfonts = false
sudo = false

[install]
alacritty = false
bat = false
bottom = false
build_essential = false
cmake = false
codex = false
docker = false
fd = false
flatpak = false
fnm = false
fzf = false
ghostty = false
gnome_tweaks = false
go = false
iproute2 = false
iterm2 = false
karabiner = false
kitty = false
lf = false
lsd = false
mods = false
neofetch = false
neovim = false
ninja = false
nmap = false
node = false
nushell = false
perl = false
python = false
ripgrep = false
ruby = false
rust = false
sd = false
shellcheck = false
snap = false
starship = false
tinty = false
tldr = false
tmux = false
tree = false
uv = false
wezterm = false
wget = false
wireguard = false
wireshark = false
xclip = false
zellij = false
zsh = false
