[platform]
distro = ""
vm = false
sudo = false
gui = false
apt = false
brew = false
snap = false
fontsize = 17.0
nerdfonts = false
hostname = ""

[xdg]
config_home = ""
data_home = ""
state_home = ""
cache_home = ""
log_file = ""

[install]
alacritty = false
bat = false
bottom = false
claude = false
cmake = false
codex = false
docker = false
fd = false
fzf = false
ghostty = false
go = false
iproute2 = false
iterm2 = false
karabiner = false
kitty = false
lf = false
lsd = false
mods = false
neovim = false
ninja = false
nmap = false
node = false
nushell = false
pi = false
python = false
ripgrep = false
ruby = false
rust = false
sd = false
shellcheck = false
starship = false
tinty = false
tldr = false
tmux = false
tree = false
uv = false
wezterm = false
wget = false
wireguard = false
zellij = false
zsh = false
