{{- if and (eq .chezmoi.os "linux") .install.nerdfonts }}

['.local/share/fonts/FiraCode']
type = 'archive'
url = 'https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.tar.xz'
extract = true
include = ['*.ttf']

['.local/share/fonts/Meslo']
type = 'archive'
url = 'https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.tar.xz'
extract = true
include = ['*.ttf']

{{- end }}
