{{ if and .nerdfonts (not (contains "darwin" .osid )) }}
['.local/share/fonts/FiraCode']
type = 'archive'
url = 'https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.tar.xz'
extract = true
include = ['*.ttf']
refreshPeriod = '168h'

['.local/share/fonts/Meslo']
type = 'archive'
url = 'https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.tar.xz'
extract = true
include = ['*.ttf']
refreshPeriod = '168h'
{{ end }}

{{ if .install.fzf }}
['.local/share/fzf']
type = 'git-repo'
url = 'https://github.com/junegunn/fzf.git'
refreshPeriod = '168h'

['.local/share/tinted-theming/base16-fzf']
type = 'git-repo'
url = 'https://github.com/tinted-theming/base16-fzf.git'
refreshPeriod = '168h'
{{ end }}

['.local/share/tinted-theming/base16-shell']
type = 'git-repo'
url = 'https://github.com/tinted-theming/base16-shell.git'
refreshPeriod = '168h'

{{ if .install.zsh }}
['.local/share/zsh/oh-my-zsh']
type = 'git-repo'
url = 'https://github.com/ohmyzsh/ohmyzsh.git'
refreshPeriod = '168h'

['.local/share/zsh/custom-completions/_conda']
type = 'file'
url = 'https://raw.githubusercontent.com/conda-incubator/conda-zsh-completion/master/_conda'
refreshPeriod = '168h'

['.local/share/zsh/zsh-completions']
type = 'archive'
{{ $tag := (gitHubLatestRelease "zsh-users/zsh-completions").TagName }}
url = 'https://github.com/zsh-users/zsh-completions/archive/refs/tags/{{ $tag }}.tar.gz'
exact = true
stripComponents = 2
include = ['*/src/_*']

['.local/share/zsh/zsh-autosuggestions']
type = 'git-repo'
url = 'https://github.com/zsh-users/zsh-autosuggestions.git'
refreshPeriod = '168h'

['.local/share/zsh/zsh-syntax-highlighting']
type = 'git-repo'
url = 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
refreshPeriod = '168h'

['.local/share/zsh/zsh-vi-mode']
type = 'git-repo'
url = 'https://github.com/jeffreytse/zsh-vi-mode.git'
refreshPeriod = '168h'

['.local/share/zsh/powerlevel10k']
type = 'git-repo'
url = 'https://github.com/romkatv/powerlevel10k.git'
refreshPeriod = '168h'
{{ end }}
