#!/usr/bin/env bash

# Interactive login shells should run bashrc, this is why we source it in
# 'bash_profile'. However, we don't want non-interactive login shells to run
# bashrc. Thats why we get out of here if non-interactive
[[ -z "$PS1" ]] && return

# Source environment file. Not the best place to do since non-interactive shells
# don't run bashrc. But there is no perfect place in bash...
[ -f "$XDG_CONFIG_HOME/shell/env" ] && source "$XDG_CONFIG_HOME/shell/env"

# Source alias file
[ -f "$XDG_CONFIG_HOME/shell/aliases" ] && source "$XDG_CONFIG_HOME/shell/aliases"

# Remove macOS's "we now use zsh" warning at startup
export BASH_SILENCE_DEPRECATION_WARNING=1

# XDG path for bash history file
export HISTFILE="$XDG_STATE_HOME"/bash/history

# Use extended globs.
shopt -s extglob

# Append to the history file, don't overwrite it.
shopt -s histappend

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# Increase bash history
HISTSIZE=1000
HISTFILESIZE=2000

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Nice prompt.
eval "$(starship init bash)"

# BASE16 colors.
[ -n "$PS1" ] && [ -s "$BASE16_SHELL_PATH/profile_helper.sh" ] && \
    source "$BASE16_SHELL_PATH/profile_helper.sh"

# Activate FZF.
[ -f "$XDG_CONFIG_HOME/fzf/fzf.bash" ] && source "$XDG_CONFIG_HOME/fzf/fzf.bash"

# Load custom shell functions.
if [ -d "$XDG_CONFIG_HOME/shell/functions" ]; then
    for file in "$XDG_CONFIG_HOME/shell/functions"/*; do
        # Ensure that the file is readable and a regular file (not a directory)
        # before attempting to source it
        [ -r "$file" ] && [ -f "$file" ] && source "$file"
    done
fi
