#!/usr/bin/env bash

# NOTE: We avoid sourcing the environment here because it's already
# sourced in bash_profile. When bash is
# 1. default shell on macOS: bash_profile is executed for each new shell.
# 2. default shell on Linux: bash_profile was executed during login.
# 3. subshell on any OS: bash_profile is NOT executed, expecting the
#    parent shell to have already sourced the environment.

# Ensure only interactive login shells source bashrc. Non-interactive shells
# (like the inital login shell on linux) should not perform the interactive
# configurations typically found in bashrc.
[[ -z "$PS1" ]] && return

# Source alias file
[ -f "$XDG_CONFIG_HOME/shell/aliases" ] && source "$XDG_CONFIG_HOME/shell/aliases"

# Remove macOS's "we now use zsh" warning at startup
export BASH_SILENCE_DEPRECATION_WARNING=1

# XDG path for bash history file
export HISTFILE="$XDG_STATE_HOME"/bash/history

# Use extended globs.
shopt -s extglob

# Append to the history file, don't overwrite it.
shopt -s histappend

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# Increase bash history
HISTSIZE=1000
HISTFILESIZE=2000

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Nice prompt.
if command -v starship &> /dev/null; then
    eval "$(starship init bash)"
fi

# BASE16 colors. NOTE: Base16-shell is configured and initalized in zshrc. Bash
# simply executes the theme when zsh initialized it before.
[ -s "$BASE16_SHELL_PATH/profile_helper.sh" ] && \
    source "$BASE16_SHELL_PATH/profile_helper.sh"

# Activate FZF.
[ -f "$XDG_CONFIG_HOME/fzf/fzf.bash" ] && source "$XDG_CONFIG_HOME/fzf/fzf.bash"

# Load custom shell functions.
if [ -d "$XDG_CONFIG_HOME/shell/functions" ]; then
    for file in "$XDG_CONFIG_HOME/shell/functions"/*; do
        # Ensure that the file is readable and a regular file (not a directory)
        # before attempting to source it
        [ -r "$file" ] && [ -f "$file" ] && source "$file"
    done
fi
