#!/usr/bin/env bash

# Ensure only interactive login shells source bashrc. Non-interactive shells
# (like the inital login shell on linux) should not perform the interactive
# configurations typically found in bashrc.
[[ -z "$PS1" ]] && return

# Source shell-independent environment variables in bashrc instead of
# bash_profile for better compatibility. The performance impact negligible.
[ -f "$HOME/.config/shell/env" ] && source "$HOME/.config/shell/env"

# Source alias file
[ -f "$XDG_CONFIG_HOME/shell/aliases" ] && source "$XDG_CONFIG_HOME/shell/aliases"

# Remove macOS's "we now use zsh" warning at startup
export BASH_SILENCE_DEPRECATION_WARNING=1

# XDG path for bash history file
export HISTFILE="$XDG_STATE_HOME"/bash/history

# Use extended globs.
shopt -s extglob

# Append to the history file, don't overwrite it.
shopt -s histappend

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# Increase bash history
HISTSIZE=1000
HISTFILESIZE=2000

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Nice prompt.
if command -v starship &> /dev/null; then
    eval "$(starship init bash)"
fi

# Activate FZF
if command -v fzf &> /dev/null; then
    eval "$(fzf --bash)"
fi

# tinted-theming for fzf
[[ -s "$XDG_DATA_HOME/tinted-theming/tinty/artifacts/tinted-fzf-sh-file.sh" ]] \
    && source "$XDG_DATA_HOME/tinted-theming/tinty/artifacts/tinted-fzf-sh-file.sh" 

# Load custom shell functions.
if [ -d "$XDG_CONFIG_HOME/shell/functions" ]; then
    for file in "$XDG_CONFIG_HOME/shell/functions"/*; do
        # Ensure that the file is readable and a regular file (not a directory)
        # before attempting to source it
        [ -r "$file" ] && [ -f "$file" ] && source "$file"
    done
fi
