#!/usr/bin/env bash

set -euo pipefail
source ~/.local/share/chezmoi/.script_helper
source ~/.config/shell/env

if has brew; then
    info 'Update homebrew'
    brew update
else
    info 'Install homebrew'
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

eval "$(/opt/homebrew/bin/brew shellenv)"

info 'Install formulas from Brewfile'
brew bundle --file="$XDG_CONFIG_HOME/homebrew/Brewfile"
